# Exploring the data

### Working with tabular data

In [56]:
import arcpy
import pandas as pd
import os

# Read the data and store it in a pandas dataframe, df.  
# A data frame is a 2-dimensional data structure.  
    
projectDir = r"C:\Users\echoi4\Desktop\New\esterArcGISProject-20230428T013544Z-001\esterArcGISProject" ## Replace with your data directory


try:
    # When working inside ArcGIS Pro,
    # use the project name "CURRENT"
    aprx = arcpy.mp.ArcGISProject("CURRENT")
except:
    # When working outside of ArcGIS Pro,
    # use the project full path file name.
    aprx = arcpy.mp.ArcGISProject(project_dir + "/estherArcGISProject.aprx")


workingDir = projectDir + "\output\\"
visDir = workingDir + "\pics\\"

# Create output directories if they don't already exist.
dirs = [workingDir, visDir]
for d in dirs:
    if not os.path.exists(d):
        os.mkdir(d)

myData = projectDir + '\e.csv'
df = pd.read_csv(myData, header=0)

# Print the first 5 records to get a feel for the data.
df.head()

[56]:31: DtypeWarning: Columns (20,52,55,73,79,86,88,92,99,104) have mixed types. Specify dtype option on import or set low_memory=False.

       Query Id  ...       Datee
0  2.000314e+09  ...    1/1/2022
1  2.000314e+09  ...    1/1/2022
2  2.000314e+09  ...  12/31/2021
3  2.000314e+09  ...  12/31/2021
4  2.000314e+09  ...  12/31/2021

[5 rows x 106 columns]

In [57]:
# What fields does the data have?
df.columns

Index(['Query Id', 'Query Name', 'Date', 'Title', 'Url', 'Domain', 'Sentiment',
       'Page Type', 'Language', 'Country Code',
       ...
       'Reddit Author Karma', 'Reddit Score', 'Region', 'Region Code',
       'Root Blog Name', 'Root Post Id', 'Subreddit', 'Subreddit Subscribers',
       'Weblog Title', 'Datee'],
      dtype='object', length=106)

In [58]:
# Print ALL the field names.
for columnName in df.columns:
    print(columnName,end='        ',)

Query Id        Query Name        Date        Title        Url        Domain        Sentiment        Page Type        Language        Country Code        Continent Code        Continent        Country        City Code        Account Type        Added        Assignment        Author        Avatar        Category Details        Checked        City        Display URLs        Expanded URLs        Facebook Author ID        Facebook Comments        Facebook Likes        Facebook Role        Facebook Shares        Facebook Subtype        Full Name        Full Text        Gender        Hashtags        Impact        Impressions        Instagram Comments        Instagram Followers        Instagram Following        Instagram Interactions Count        Instagram Likes        Instagram Posts        Interest        Last Assignment Date        Latitude        Location Name        Longitude        Media Filter        Media URLs        Mentioned Authors        Original Url        Priority        Professions        Resource Id        Short URLs        Starred        Status        Subtype        Thread Author        Thread Created Date        Thread Entry Type        Thread Id        Thread URL        Total Monthly Visitors        Twitter Author ID        Twitter Channel Role        Twitter Followers        Twitter Following        Twitter Reply Count        Twitter Reply to        Twitter Retweet of        Twitter Retweets        Twitter Tweets        Twitter Verified        Updated        Reach (new)        Blog Name        Copyright        Engagement Type        Entity Info        Item Review        Linkedin Comments        Linkedin Engagement        Linkedin Impressions        Linkedin Likes        Linkedin Shares        Linkedin Sponsored        Linkedin Video Views        Page Type Name        Parent Blog Name        Parent Post Id        Pub Type        Publisher Sub Type        Rating        Reddit Author Awardee Karma        Reddit Author Awarder Karma        Reddit Author Karma        Reddit Score        Region        Region Code        Root Blog Name        Root Post Id        Subreddit        Subreddit Subscribers        Weblog Title        Datee

In [59]:
# How many columns and rows does the data have?
df.shape

(8241, 106)

In [60]:
# Which countries are there in the "Country" field?
# The Series method named unique returns a Numpy array containing the unique values in a series. 
df['Country'].unique()

array(['Seychelles', 'Kenya', 'Italy', 'Australia', 'Singapore', 'Spain',
       nan, 'Russia', 'Brazil', 'Netherlands', 'United Kingdom', 'Chile',
       'Germany', 'Zimbabwe', 'China', 'Nigeria', 'Cambodia', 'Romania',
       'Azerbaijan', 'United States of America', 'Turkey', 'Argentina',
       'Switzerland', 'Ghana', 'South Africa', 'Uganda', 'Indonesia',
       'Democratic Republic of the Congo', 'Botswana', 'Belgium',
       'Saudi Arabia', 'Ukraine', 'Thailand', 'France', 'Greece',
       'Hungary', 'Bosnia and Herzegovina', 'Republic of Serbia', 'Japan',
       'United Republic of Tanzania', 'Poland', 'Morocco', 'Mexico',
       'Iran', 'Lebanon', 'United Arab Emirates', 'Peru', 'Zambia',
       'Venezuela', 'Tunisia', 'India', 'New Zealand', 'Taiwan',
       'Somalia', 'Norway', 'Dominican Republic', 'Kazakhstan',
       'Ethiopia', 'Paraguay', 'Colombia', 'Cape Verde', 'Angola',
       'Portugal', 'Ivory Coast', 'Aruba', 'Oman', 'Slovakia', 'Namibia',
       'Canada', 'Jordan', 'North Macedonia',
       'British Indian Ocean Territory', 'South Korea', 'Cayman Islands',
       'Cameroon', 'Kyrgyzstan', 'Jamaica', 'Bangladesh', 'Algeria',
       'Mozambique', 'Malta', 'Armenia', 'Burkina Faso', 'Eritrea',
       'Monaco', 'Vietnam', 'Sweden', 'Senegal', 'Turkmenistan',
       'Czech Republic', 'Panama', 'Republic of Ireland', 'Brunei',
       'Malawi', 'Malaysia', 'Philippines', 'Pakistan', 'Mongolia',
       'Luxembourg', 'Finland', 'Mauritius', 'Tajikistan', 'Austria',
       'Egypt', 'Bulgaria', 'Rwanda', 'Croatia', 'British Virgin Islands',
       'Ecuador', 'Uruguay', 'Uzbekistan', 'Moldova', 'Yemen', 'Iraq',
       'Kuwait', 'Nepal', 'Nicaragua', 'Sierra Leone', 'Hong Kong S.A.R.',
       'Israel', 'Niger', 'Guam', 'Macao S.A.R', 'Slovenia', 'Costa Rica',
       'Guatemala', 'Bolivia', 'Denmark', 'Puerto Rico', 'Honduras',
       'Sao Tome and Principe', 'Dominica', 'Saint Kitts and Nevis',
       'Isle of Man'], dtype=object)

In [61]:
# Change the name in the Country column for USA to match GIS data name for USA
df['Country'] = df['Country'].replace('United States of America','United States')
df['Country'].unique()

array(['Seychelles', 'Kenya', 'Italy', 'Australia', 'Singapore', 'Spain',
       nan, 'Russia', 'Brazil', 'Netherlands', 'United Kingdom', 'Chile',
       'Germany', 'Zimbabwe', 'China', 'Nigeria', 'Cambodia', 'Romania',
       'Azerbaijan', 'United States', 'Turkey', 'Argentina',
       'Switzerland', 'Ghana', 'South Africa', 'Uganda', 'Indonesia',
       'Democratic Republic of the Congo', 'Botswana', 'Belgium',
       'Saudi Arabia', 'Ukraine', 'Thailand', 'France', 'Greece',
       'Hungary', 'Bosnia and Herzegovina', 'Republic of Serbia', 'Japan',
       'United Republic of Tanzania', 'Poland', 'Morocco', 'Mexico',
       'Iran', 'Lebanon', 'United Arab Emirates', 'Peru', 'Zambia',
       'Venezuela', 'Tunisia', 'India', 'New Zealand', 'Taiwan',
       'Somalia', 'Norway', 'Dominican Republic', 'Kazakhstan',
       'Ethiopia', 'Paraguay', 'Colombia', 'Cape Verde', 'Angola',
       'Portugal', 'Ivory Coast', 'Aruba', 'Oman', 'Slovakia', 'Namibia',
       'Canada', 'Jordan', 'North Macedonia',
       'British Indian Ocean Territory', 'South Korea', 'Cayman Islands',
       'Cameroon', 'Kyrgyzstan', 'Jamaica', 'Bangladesh', 'Algeria',
       'Mozambique', 'Malta', 'Armenia', 'Burkina Faso', 'Eritrea',
       'Monaco', 'Vietnam', 'Sweden', 'Senegal', 'Turkmenistan',
       'Czech Republic', 'Panama', 'Republic of Ireland', 'Brunei',
       'Malawi', 'Malaysia', 'Philippines', 'Pakistan', 'Mongolia',
       'Luxembourg', 'Finland', 'Mauritius', 'Tajikistan', 'Austria',
       'Egypt', 'Bulgaria', 'Rwanda', 'Croatia', 'British Virgin Islands',
       'Ecuador', 'Uruguay', 'Uzbekistan', 'Moldova', 'Yemen', 'Iraq',
       'Kuwait', 'Nepal', 'Nicaragua', 'Sierra Leone', 'Hong Kong S.A.R.',
       'Israel', 'Niger', 'Guam', 'Macao S.A.R', 'Slovenia', 'Costa Rica',
       'Guatemala', 'Bolivia', 'Denmark', 'Puerto Rico', 'Honduras',
       'Sao Tome and Principe', 'Dominica', 'Saint Kitts and Nevis',
       'Isle of Man'], dtype=object)

In [62]:
# How many countries is that?
# Use the built-in len method to find the length of the array of unique country names.
print(len(df['Country'].unique()))

134

In [22]:
# The Page Type column indicates the detected data source (e.g., reddit, twitter, news,...)
## Add code to determine which page types are there in the "Page Type" field.

In [23]:
# How many page types are there?
## Add code to print the number of unique page types.

### Exploring text content 
Suppose we want to search for references to vegans or happiness in the Tweets.  We can use regular expressions to search for key words.  A _regular expression_ is a sequence of characters that specifies a search pattern in text (It's a very deep topic. This provides a gentle introduction: [How to use Regex in Pandas](https://kanoki.org/2019/11/12/how-to-use-regex-in-pandas/)).  The code below has a simple regular expression that uses | to mean 'or':

In [63]:
regular_expression = 'happy|vegan|happiness|joy|smile'

# Get a dataframe of records in which the content of the Full Text column has any of these terms. 

# For the moment, we only care about the column that contains the full text of the posts.
# To make a series from a particular columns, you can specify the column name in square braces
ft_series = df['Full Text']
print(ft_series.size)

# Prepare a dataframe that only has the non-null Tweets 
ft_series = ft_series.dropna()
print(ft_series.size)


# str.contains returns a Boolean series.  A series is a one dimensional data structure, like an array.
#boolean_series = df2['Full Text'].str.contains(regular_expression, case=False)
boolean_series = ft_series.str.contains(regular_expression, case=False)

# loc is a dataframe property that allows you to access a group of rows and/or columns 
# based either on labels or a boolean array.
# Here we're using it with the Boolean series to get the Tweets that match our terms 
# (the ones where str.contains returned True).
joy_series = ft_series.loc[boolean_series]

joy_series= joy_series.drop_duplicates()
print(joy_series.size)
joy_series.head()

8241
8239
13

71      We're Always Happy to visit our Farmers and Of...
625     RT @aurbaneja15 Finding an effective biologica...
1620    RT @ValentBioSci Happy #DiPel50 Anniversary Th...
1634    Happy #DiPel50 Anniversary Thursday! Today's s...
2656    Finding an effective biological control agent ...
Name: Full Text, dtype: object

### Extract date time info. (year, month, day, or time) with the Python datetime module.

In [64]:
import datetime
theDate = '06/14/2015  4:11:11 PM'
# Create a string that represents the format of the date.  
# The format code tells it where to look for each element. 
# For example, %m represents *month*, whereas %M represents *minute*.
# A full table of format codes can be found here:  (Python strptime)[https://www.programiz.com/python-programming/datetime/strptime]
# The datetime module's datetime class method named *strptime* stands for string parsed time.
datem = datetime. datetime. strptime(theDate, '%m/%d/%Y %H:%M:%S %p')
print(datem.year)

2015

### Working with dates in Pandas

Dataframes have a DatetimeIndex class that makes it easy to extract the parts of a date or time from a date time stamp.

In [26]:
# So many columns... does it have a Date column?
"Date" in df.columns

True

In [27]:
# How about a Year column?
"Year" in df.columns

False

In [65]:
# Extract Year from the Date column and make new columns for these.
df['Year'] = pd.DatetimeIndex(df['Datee']).month
df.columns

Index(['Query Id', 'Query Name', 'Date', 'Title', 'Url', 'Domain', 'Sentiment',
       'Page Type', 'Language', 'Country Code',
       ...
       'Reddit Score', 'Region', 'Region Code', 'Root Blog Name',
       'Root Post Id', 'Subreddit', 'Subreddit Subscribers', 'Weblog Title',
       'Datee', 'Year'],
      dtype='object', length=107)

In [ ]:
## Write code here to add a Month column to the dataframe (df)

In [66]:
# Let's check which years are included in the data. 
# The Series method named unique returns a Numpy array containing the unique values in a series. 
df['Year'].unique()

array([ 1, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2], dtype=int64)

In [ ]:
# Now we have years!  Let's find out how many Canadian posts there were in 2021.
# To select the 2021 Canadian posts, we need to select rows based on two column conditions. 
#df_special = df[(df['Year'] == 2021) & (df['Country']== 'Canada')]

boolean_series = (df['Year'] == 2019) & (df['Country']== 'Canada')
df_CA_21 = df[boolean_series]
df_CA_21.shape

### Select columns / rows to a csv to be joined with the country boundaries.

In [67]:
# Select pertinent columns.
df_small = df[['Page Type','Country', 'Year', 'Full Text']]  ## Add the month column 

# Print the number of rows and columns.
print(df_small.shape)

# Remove rows in which any of the values are empty.
df_small = df_small.dropna()

print(df_small.shape)

smallCSV = workingDir + 'esther_reduced.csv'
df_small.to_csv(smallCSV)

(8241, 4)
(6592, 4)

In [68]:
# Explore the reduced dataset.
# The value_counts method provides a frequency count of values in a field.  
# As you can see below, 2016 was a big year for Esther the Pig. 
print(df_small['Year'].value_counts())

12    955
5     690
7     670
2     632
6     610
9     556
8     495
10    482
11    475
3     378
4     338
1     311
Name: Year, dtype: int64

In [32]:
# Explore the reduced dataset.
# Where is Esther most discussed?
## Add code to print the frequency count for Country.

In [69]:
# Explore the reduced dataset.
# Which countries have postings each year? 
for val in sorted(df_small['Year'].unique()):
    # selecting rows based on condition
    rslt_df = df_small[df_small['Year'] == val]
    print(f'Year:   {val}')
    print(rslt_df['Country'].unique())

Year:   1
['Seychelles' 'Kenya' 'Greece' 'United Kingdom' 'Czech Republic' 'Italy'
 'Netherlands' 'Azerbaijan' 'British Virgin Islands' 'Russia' 'Bulgaria'
 'Spain' 'United States' 'Romania' 'India' 'Ecuador' 'Portugal' 'China'
 'Brazil' 'Armenia' 'Panama' 'Venezuela' 'Ukraine' 'Zimbabwe' 'Jordan'
 'Tajikistan' 'France' 'Republic of Serbia' 'Belgium' 'North Macedonia'
 'Kyrgyzstan' 'Nigeria' 'Chile' 'Argentina' 'South Africa' 'Morocco'
 'Turkey' 'Ghana' 'United Republic of Tanzania' 'Kazakhstan' 'Uganda'
 'Germany' 'Algeria' 'Poland']
Year:   2
['France' 'Ivory Coast' 'Italy' 'Bulgaria' 'Brazil' 'Russia' 'Spain'
 'Kenya' 'South Africa' 'United States' 'Netherlands' 'Zimbabwe' 'Namibia'
 'Ghana' 'Uganda' 'Nigeria' 'Australia' 'Senegal' 'Portugal' 'Croatia'
 'India' 'Romania' 'Azerbaijan' 'United Republic of Tanzania' 'Rwanda'
 'Argentina' 'Canada' 'Turkey' 'Armenia' 'China' 'Poland' 'Germany'
 'United Kingdom' 'Tajikistan' 'Ethiopia' 'Mozambique' 'Colombia'
 'New Zealand' 'Austria' 'Switzerland' 'Dominican Republic' 'Costa Rica'
 'Venezuela' 'Greece' 'Mexico' 'Isle of Man' 'Jordan' 'Ukraine' 'Uruguay'
 'Nicaragua' 'United Arab Emirates' 'Philippines' 'Republic of Serbia'
 'Japan' 'Somalia' 'Panama' 'Pakistan' 'Sweden' 'Botswana' 'Hungary']
Year:   3
['Romania' 'Russia' 'Republic of Ireland' 'Spain' 'Switzerland'
 'United States' 'Czech Republic' 'Netherlands' 'Ukraine' 'China' 'Kenya'
 'France' 'Chile' 'Turkey' 'Italy' 'Malawi' 'Bulgaria' 'Hungary'
 'South Africa' 'United Kingdom' 'Armenia' 'Venezuela' 'Greece' 'Brazil'
 'Azerbaijan' 'Argentina' 'Australia' 'Jordan' 'Germany' 'Poland'
 'Nigeria' 'Belgium' 'Canada' 'United Arab Emirates' 'India' 'Uganda'
 'Thailand' 'Ivory Coast' 'Zimbabwe' 'Portugal' 'Dominican Republic'
 'Morocco' 'Dominica' 'Saint Kitts and Nevis']
Year:   4
['Spain' 'Russia' 'United States' 'Italy' 'France' 'Tajikistan' 'Romania'
 'Kenya' 'Turkey' 'Portugal' 'Argentina' 'Slovakia' 'Venezuela' 'Nigeria'
 'China' 'South Africa' 'Switzerland' 'Republic of Serbia'
 'Republic of Ireland' 'Ukraine' 'Germany' 'Mozambique' 'Jordan'
 'Azerbaijan' 'Japan' 'Hungary' 'Zimbabwe' 'Ethiopia' 'Austria' 'Egypt'
 'Belgium' 'Chile' 'Malaysia' 'Netherlands' 'United Republic of Tanzania'
 'Bulgaria' 'Cameroon' 'Rwanda' 'Botswana' 'Mexico' 'Algeria' 'Australia'
 'United Arab Emirates' 'Brazil' 'Oman' 'United Kingdom' 'Greece' 'Taiwan'
 'Israel' 'Slovenia']
Year:   5
['South Africa' 'Mexico' 'Spain' 'Russia' 'Australia' 'Canada'
 'United States' 'United Kingdom' 'Italy' 'Algeria' 'Venezuela'
 'United Arab Emirates' 'Ghana' 'Portugal' 'Kenya' 'Thailand'
 'United Republic of Tanzania' 'Romania' 'Zimbabwe' 'Netherlands'
 'Azerbaijan' 'Switzerland' 'Kazakhstan' 'Ukraine' 'Namibia' 'India'
 'Vietnam' 'Turkey' 'Germany' 'France' 'Republic of Serbia' 'Nigeria'
 'Brunei' 'New Zealand' 'China' 'Cambodia' 'Malawi' 'Ethiopia' 'Malaysia'
 'Philippines' 'Pakistan' 'Bangladesh' 'Mongolia' 'Singapore' 'Luxembourg'
 'Brazil' 'Argentina' 'Greece' 'Finland' 'Chile' 'Mauritius' 'Hungary'
 'Armenia' 'Mozambique' 'Japan' 'Czech Republic' 'South Korea'
 'Sao Tome and Principe' 'Dominican Republic' 'Nepal'
 'Republic of Ireland' 'Democratic Republic of the Congo' 'Colombia'
 'Morocco' 'Malta' 'Uganda' 'Belgium' 'Poland']
Year:   6
['Azerbaijan' 'Republic of Serbia' 'Russia' 'Kenya' 'Monaco' 'Netherlands'
 'Australia' 'Slovakia' 'United States' 'Spain' 'Nigeria' 'Turkey'
 'Romania' 'Portugal' 'Italy' 'Greece' 'South Africa' 'United Kingdom'
 'Brazil' 'Chile' 'Vietnam' 'France' 'Germany' 'Zimbabwe' 'Sweden'
 'Ethiopia' 'Argentina' 'Botswana' 'United Republic of Tanzania'
 'North Macedonia' 'Jordan' 'Switzerland' 'Iran' 'Mozambique' 'China'
 'Senegal' 'Turkmenistan' 'Czech Republic' 'India' 'Algeria' 'Indonesia'
 'Panama' 'Colombia' 'Republic of Ireland'
 'Democratic Republic of the Congo' 'Uganda' 'Belgium' 'Hungary' 'Mexico'
 'Taiwan' 'Lebanon' 'Saudi Arabia' 'Canada' 'Japan' 'Croatia' 'Cape Verde'
 'Zambia' 'Peru' 'Ukraine' 'United Arab Emirates' 'Honduras' 'Pakistan']
Year:   7
['Turkey' 'Azerbaijan' 'Ukraine' 'United States' 'Russia'
 'Bosnia and Herzegovina' 'Spain' 'Italy' 'China' 'Seychelles' 'Greece'
 'United Kingdom' 'South Africa' 'Kenya' 'Burkina Faso' 'Brazil'
 'Colombia' 'Cape Verde' 'Republic of Serbia' 'Netherlands' 'Australia'
 'France' 'Belgium' 'Chile' 'Argentina' 'Mexico' 'Venezuela' 'Armenia'
 'Portugal' 'Ethiopia' 'Romania' 'Germany' 'North Macedonia'
 'United Republic of Tanzania' 'Zimbabwe' 'Nigeria' 'Eritrea' 'Slovakia'
 'Kazakhstan' 'Lebanon' 'Jamaica' 'Canada' 'Hungary' 'Angola' 'Algeria'
 'Denmark' 'Morocco' 'Uganda' 'Puerto Rico' 'Mozambique' 'Bolivia']
Year:   8
['Argentina' 'India' 'Netherlands' 'Kenya' 'Russia' 'Japan' 'Italy'
 'United Republic of Tanzania' 'Hungary' 'Switzerland' 'Turkey' 'Brazil'
 'Spain' 'Jamaica' 'Zimbabwe' 'South Africa' 'France' 'Australia'
 'Ukraine' 'Bangladesh' 'United States' 'Algeria' 'Morocco' 'Namibia'
 'Romania' 'Seychelles' 'Mozambique' 'United Kingdom' 'Ethiopia'
 'Cape Verde' 'North Macedonia' 'Germany' 'Chile' 'Portugal'
 'Republic of Serbia' 'Greece' 'Mexico' 'Azerbaijan' 'Taiwan' 'Canada'
 'Malta' 'China' 'Armenia' 'Rwanda' 'Botswana' 'Bosnia and Herzegovina'
 'Slovakia' 'Angola' 'Costa Rica' 'Uganda' 'Venezuela' 'Mongolia'
 'Kazakhstan' 'Nigeria' 'Ecuador' 'Panama' 'Uruguay' 'Peru' 'Guatemala'
 'Colombia' 'Bolivia' 'Republic of Ireland' 'Moldova' 'Zambia']
Year:   9
['Netherlands' 'Spain' 'Italy' 'Zimbabwe' 'United Kingdom' 'Greece'
 'Angola' 'United States' 'Ukraine' 'Kenya' 'France' 'Romania' 'Oman'
 'Venezuela' 'Nigeria' 'Germany' 'Morocco' 'Brazil' 'Cape Verde'
 'Slovakia' 'China' 'Seychelles' 'Switzerland' 'Russia' 'Poland'
 'Australia' 'Namibia' 'South Africa' 'Mexico'
 'United Republic of Tanzania' 'Ghana' 'Portugal' 'India' 'Canada'
 'Jordan' 'North Macedonia' 'Colombia' 'British Indian Ocean Territory'
 'South Korea' 'Uganda' 'Turkey' 'Cayman Islands' 'Cameroon' 'Kyrgyzstan'
 'New Zealand' 'Argentina' 'Malaysia' 'Mongolia' 'Croatia'
 'Republic of Serbia' 'Bosnia and Herzegovina' 'Paraguay' 'Slovenia'
 'Iran' 'Indonesia' 'Malta']
Year:   10
['Zimbabwe' 'Argentina' 'United States' 'Spain' 'Greece' 'Kenya'
 'Netherlands' 'Kazakhstan' 'Australia' 'United Republic of Tanzania'
 'Ukraine' 'Russia' 'Ethiopia' 'South Africa' 'Italy' 'Zambia' 'Paraguay'
 'China' 'Nigeria' 'Colombia' 'Uganda' 'Venezuela' 'Brazil'
 'United Kingdom' 'Cape Verde' 'Angola' 'Mexico' 'Romania' 'Portugal'
 'Chile' 'Ivory Coast' 'Seychelles' 'Turkey' 'Aruba' 'Mozambique' 'Malawi'
 'Iran' 'Armenia' 'Israel' 'Ecuador' 'Senegal' 'Morocco' 'France'
 'Austria' 'Ghana' 'Taiwan' 'Niger' 'India' 'Guam' 'Germany' 'Belgium'
 'Rwanda' 'Pakistan' 'Tajikistan' 'Macao S.A.R']
Year:   11
['Brazil' 'Netherlands' 'United States' 'Australia' 'Thailand' 'Singapore'
 'Spain' 'Japan' 'United Republic of Tanzania' 'Kenya' 'Greece' 'Turkey'
 'Poland' 'Morocco' 'Mexico' 'Italy' 'Iran' 'South Africa' 'Hungary'
 'France' 'Russia' 'Germany' 'Azerbaijan' 'Lebanon' 'Romania'
 'United Arab Emirates' 'Zimbabwe' 'Peru' 'Nigeria' 'Zambia' 'Venezuela'
 'Argentina' 'Seychelles' 'Switzerland' 'United Kingdom' 'China' 'Tunisia'
 'Uganda' 'Belgium' 'India' 'Ukraine' 'New Zealand' 'Taiwan' 'Somalia'
 'Norway' 'Dominican Republic' 'Portugal' 'Paraguay' 'Nicaragua' 'Algeria'
 'Ghana' 'Sierra Leone' 'Namibia' 'Chile' 'Hong Kong S.A.R.' 'Ethiopia'
 'Colombia']
Year:   12
['Seychelles' 'Italy' 'Australia' 'Singapore' 'Spain' 'Russia' 'Brazil'
 'Netherlands' 'United Kingdom' 'Chile' 'Germany' 'Kenya' 'Zimbabwe'
 'China' 'Nigeria' 'Cambodia' 'Romania' 'Azerbaijan' 'United States'
 'Turkey' 'Argentina' 'Switzerland' 'Ghana' 'South Africa' 'Uganda'
 'Indonesia' 'Democratic Republic of the Congo' 'Botswana' 'Belgium'
 'Saudi Arabia' 'Ukraine' 'Thailand' 'France' 'Greece' 'Hungary'
 'Bosnia and Herzegovina' 'Republic of Serbia' 'Bulgaria' 'Jordan'
 'Zambia' 'Vietnam' 'Pakistan' 'India' 'Armenia' 'Kazakhstan' 'Canada'
 'United Republic of Tanzania' 'Rwanda' 'Mozambique' 'Dominican Republic'
 'Namibia' 'Uruguay' 'Malaysia' 'Czech Republic' 'Tajikistan' 'Colombia'
 'Uzbekistan' 'Moldova' 'South Korea' 'Yemen' 'Iraq' 'Oman' 'Peru' 'Egypt'
 'Kuwait' 'Nepal' 'Mexico']

### Make a copy of the worldwide countries dataset

Other data will be joined to this, so we want to preserve the original before modifying the table.

Data source: 
[ArcGIS Hub World Countries Generalized] (https://hub.arcgis.com/datasets/2b93b06dc0dc4e809d3c8db5cb96ba69_0/explore?location=-0.101905%2C0.000000%2C2.09)

In [70]:
import arcpy
arcpy.env.workspace = projectDir + r'esterArcGISProject.gdb'
arcpy.env.overwriteOutput = True
worldData = 'world_countries'
worldDataCopy = workingDir + 'worldEsther.shp'
arcpy.CopyFeatures_management(worldData, worldDataCopy)

In [71]:
# Get a the base name (without the extention) of the input data.  We'll use this to name files in the next part.
baseName = os.path.basename(myData)
baseName = os.path.splitext(baseName)[0]
baseName

'e'

### Create a table for each time step and join the tables with the GIS data

In [72]:
# Create an empty dictionary to store the number of records per year.
yearly_count = {}

# For each year in the reduced dataset, create a csv file.

for yr in sorted(df_small['Year'].unique()):
    # Select rows based on the year
    rslt_df = df_small[df_small['Year'] == yr]
    print(f"Number of records in {yr}: {len(rslt_df)}")
    yearly_count[yr] = len(rslt_df)

    # Prepare an output name
    annualCSV = workingDir + f'{baseName}{yr}.csv'
    
    # Write the data frame to csv
    rslt_df.to_csv(annualCSV)
    
    print(f'Year:   {yr}')
    print(rslt_df['Country'].unique())
    
    # Join the data
    joinedData = arcpy.management.AddJoin(
        in_layer_or_view = worldDataCopy, 
        in_field = 'COUNTRY', 
        join_table = annualCSV, 
        join_field = 'Country', 
    join_type = 'KEEP_COMMON')
    
    curData = workingDir + f'{baseName}{yr}.shp'
    try:
        arcpy.CopyFeatures_management(joinedData, curData)
    except:
        print("File already exists.  New copy not created.")

Number of records in 1: 311
Year:   1
['Seychelles' 'Kenya' 'Greece' 'United Kingdom' 'Czech Republic' 'Italy'
 'Netherlands' 'Azerbaijan' 'British Virgin Islands' 'Russia' 'Bulgaria'
 'Spain' 'United States' 'Romania' 'India' 'Ecuador' 'Portugal' 'China'
 'Brazil' 'Armenia' 'Panama' 'Venezuela' 'Ukraine' 'Zimbabwe' 'Jordan'
 'Tajikistan' 'France' 'Republic of Serbia' 'Belgium' 'North Macedonia'
 'Kyrgyzstan' 'Nigeria' 'Chile' 'Argentina' 'South Africa' 'Morocco'
 'Turkey' 'Ghana' 'United Republic of Tanzania' 'Kazakhstan' 'Uganda'
 'Germany' 'Algeria' 'Poland']
Number of records in 2: 632
Year:   2
['France' 'Ivory Coast' 'Italy' 'Bulgaria' 'Brazil' 'Russia' 'Spain'
 'Kenya' 'South Africa' 'United States' 'Netherlands' 'Zimbabwe' 'Namibia'
 'Ghana' 'Uganda' 'Nigeria' 'Australia' 'Senegal' 'Portugal' 'Croatia'
 'India' 'Romania' 'Azerbaijan' 'United Republic of Tanzania' 'Rwanda'
 'Argentina' 'Canada' 'Turkey' 'Armenia' 'China' 'Poland' 'Germany'
 'United Kingdom' 'Tajikistan' 'Ethiopia' 'Mozambique' 'Colombia'
 'New Zealand' 'Austria' 'Switzerland' 'Dominican Republic' 'Costa Rica'
 'Venezuela' 'Greece' 'Mexico' 'Isle of Man' 'Jordan' 'Ukraine' 'Uruguay'
 'Nicaragua' 'United Arab Emirates' 'Philippines' 'Republic of Serbia'
 'Japan' 'Somalia' 'Panama' 'Pakistan' 'Sweden' 'Botswana' 'Hungary']
Number of records in 3: 378
Year:   3
['Romania' 'Russia' 'Republic of Ireland' 'Spain' 'Switzerland'
 'United States' 'Czech Republic' 'Netherlands' 'Ukraine' 'China' 'Kenya'
 'France' 'Chile' 'Turkey' 'Italy' 'Malawi' 'Bulgaria' 'Hungary'
 'South Africa' 'United Kingdom' 'Armenia' 'Venezuela' 'Greece' 'Brazil'
 'Azerbaijan' 'Argentina' 'Australia' 'Jordan' 'Germany' 'Poland'
 'Nigeria' 'Belgium' 'Canada' 'United Arab Emirates' 'India' 'Uganda'
 'Thailand' 'Ivory Coast' 'Zimbabwe' 'Portugal' 'Dominican Republic'
 'Morocco' 'Dominica' 'Saint Kitts and Nevis']
Number of records in 4: 338
Year:   4
['Spain' 'Russia' 'United States' 'Italy' 'France' 'Tajikistan' 'Romania'
 'Kenya' 'Turkey' 'Portugal' 'Argentina' 'Slovakia' 'Venezuela' 'Nigeria'
 'China' 'South Africa' 'Switzerland' 'Republic of Serbia'
 'Republic of Ireland' 'Ukraine' 'Germany' 'Mozambique' 'Jordan'
 'Azerbaijan' 'Japan' 'Hungary' 'Zimbabwe' 'Ethiopia' 'Austria' 'Egypt'
 'Belgium' 'Chile' 'Malaysia' 'Netherlands' 'United Republic of Tanzania'
 'Bulgaria' 'Cameroon' 'Rwanda' 'Botswana' 'Mexico' 'Algeria' 'Australia'
 'United Arab Emirates' 'Brazil' 'Oman' 'United Kingdom' 'Greece' 'Taiwan'
 'Israel' 'Slovenia']
Number of records in 5: 690
Year:   5
['South Africa' 'Mexico' 'Spain' 'Russia' 'Australia' 'Canada'
 'United States' 'United Kingdom' 'Italy' 'Algeria' 'Venezuela'
 'United Arab Emirates' 'Ghana' 'Portugal' 'Kenya' 'Thailand'
 'United Republic of Tanzania' 'Romania' 'Zimbabwe' 'Netherlands'
 'Azerbaijan' 'Switzerland' 'Kazakhstan' 'Ukraine' 'Namibia' 'India'
 'Vietnam' 'Turkey' 'Germany' 'France' 'Republic of Serbia' 'Nigeria'
 'Brunei' 'New Zealand' 'China' 'Cambodia' 'Malawi' 'Ethiopia' 'Malaysia'
 'Philippines' 'Pakistan' 'Bangladesh' 'Mongolia' 'Singapore' 'Luxembourg'
 'Brazil' 'Argentina' 'Greece' 'Finland' 'Chile' 'Mauritius' 'Hungary'
 'Armenia' 'Mozambique' 'Japan' 'Czech Republic' 'South Korea'
 'Sao Tome and Principe' 'Dominican Republic' 'Nepal'
 'Republic of Ireland' 'Democratic Republic of the Congo' 'Colombia'
 'Morocco' 'Malta' 'Uganda' 'Belgium' 'Poland']
Number of records in 6: 610
Year:   6
['Azerbaijan' 'Republic of Serbia' 'Russia' 'Kenya' 'Monaco' 'Netherlands'
 'Australia' 'Slovakia' 'United States' 'Spain' 'Nigeria' 'Turkey'
 'Romania' 'Portugal' 'Italy' 'Greece' 'South Africa' 'United Kingdom'
 'Brazil' 'Chile' 'Vietnam' 'France' 'Germany' 'Zimbabwe' 'Sweden'
 'Ethiopia' 'Argentina' 'Botswana' 'United Republic of Tanzania'
 'North Macedonia' 'Jordan' 'Switzerland' 'Iran' 'Mozambique' 'China'
 'Senegal' 'Turkmenistan' 'Czech Republic' 'India' 'Algeria' 'Indonesia'
 'Panama' 'Colombia' 'Republic of Ireland'
 'Democratic Republic of the Congo' 'Uganda' 'Belgium' 'Hungary' 'Mexico'
 'Taiwan' 'Lebanon' 'Saudi Arabia' 'Canada' 'Japan' 'Croatia' 'Cape Verde'
 'Zambia' 'Peru' 'Ukraine' 'United Arab Emirates' 'Honduras' 'Pakistan']
Number of records in 7: 670
Year:   7
['Turkey' 'Azerbaijan' 'Ukraine' 'United States' 'Russia'
 'Bosnia and Herzegovina' 'Spain' 'Italy' 'China' 'Seychelles' 'Greece'
 'United Kingdom' 'South Africa' 'Kenya' 'Burkina Faso' 'Brazil'
 'Colombia' 'Cape Verde' 'Republic of Serbia' 'Netherlands' 'Australia'
 'France' 'Belgium' 'Chile' 'Argentina' 'Mexico' 'Venezuela' 'Armenia'
 'Portugal' 'Ethiopia' 'Romania' 'Germany' 'North Macedonia'
 'United Republic of Tanzania' 'Zimbabwe' 'Nigeria' 'Eritrea' 'Slovakia'
 'Kazakhstan' 'Lebanon' 'Jamaica' 'Canada' 'Hungary' 'Angola' 'Algeria'
 'Denmark' 'Morocco' 'Uganda' 'Puerto Rico' 'Mozambique' 'Bolivia']
Number of records in 8: 495
Year:   8
['Argentina' 'India' 'Netherlands' 'Kenya' 'Russia' 'Japan' 'Italy'
 'United Republic of Tanzania' 'Hungary' 'Switzerland' 'Turkey' 'Brazil'
 'Spain' 'Jamaica' 'Zimbabwe' 'South Africa' 'France' 'Australia'
 'Ukraine' 'Bangladesh' 'United States' 'Algeria' 'Morocco' 'Namibia'
 'Romania' 'Seychelles' 'Mozambique' 'United Kingdom' 'Ethiopia'
 'Cape Verde' 'North Macedonia' 'Germany' 'Chile' 'Portugal'
 'Republic of Serbia' 'Greece' 'Mexico' 'Azerbaijan' 'Taiwan' 'Canada'
 'Malta' 'China' 'Armenia' 'Rwanda' 'Botswana' 'Bosnia and Herzegovina'
 'Slovakia' 'Angola' 'Costa Rica' 'Uganda' 'Venezuela' 'Mongolia'
 'Kazakhstan' 'Nigeria' 'Ecuador' 'Panama' 'Uruguay' 'Peru' 'Guatemala'
 'Colombia' 'Bolivia' 'Republic of Ireland' 'Moldova' 'Zambia']
Number of records in 9: 556
Year:   9
['Netherlands' 'Spain' 'Italy' 'Zimbabwe' 'United Kingdom' 'Greece'
 'Angola' 'United States' 'Ukraine' 'Kenya' 'France' 'Romania' 'Oman'
 'Venezuela' 'Nigeria' 'Germany' 'Morocco' 'Brazil' 'Cape Verde'
 'Slovakia' 'China' 'Seychelles' 'Switzerland' 'Russia' 'Poland'
 'Australia' 'Namibia' 'South Africa' 'Mexico'
 'United Republic of Tanzania' 'Ghana' 'Portugal' 'India' 'Canada'
 'Jordan' 'North Macedonia' 'Colombia' 'British Indian Ocean Territory'
 'South Korea' 'Uganda' 'Turkey' 'Cayman Islands' 'Cameroon' 'Kyrgyzstan'
 'New Zealand' 'Argentina' 'Malaysia' 'Mongolia' 'Croatia'
 'Republic of Serbia' 'Bosnia and Herzegovina' 'Paraguay' 'Slovenia'
 'Iran' 'Indonesia' 'Malta']
Number of records in 10: 482
Year:   10
['Zimbabwe' 'Argentina' 'United States' 'Spain' 'Greece' 'Kenya'
 'Netherlands' 'Kazakhstan' 'Australia' 'United Republic of Tanzania'
 'Ukraine' 'Russia' 'Ethiopia' 'South Africa' 'Italy' 'Zambia' 'Paraguay'
 'China' 'Nigeria' 'Colombia' 'Uganda' 'Venezuela' 'Brazil'
 'United Kingdom' 'Cape Verde' 'Angola' 'Mexico' 'Romania' 'Portugal'
 'Chile' 'Ivory Coast' 'Seychelles' 'Turkey' 'Aruba' 'Mozambique' 'Malawi'
 'Iran' 'Armenia' 'Israel' 'Ecuador' 'Senegal' 'Morocco' 'France'
 'Austria' 'Ghana' 'Taiwan' 'Niger' 'India' 'Guam' 'Germany' 'Belgium'
 'Rwanda' 'Pakistan' 'Tajikistan' 'Macao S.A.R']
Number of records in 11: 475
Year:   11
['Brazil' 'Netherlands' 'United States' 'Australia' 'Thailand' 'Singapore'
 'Spain' 'Japan' 'United Republic of Tanzania' 'Kenya' 'Greece' 'Turkey'
 'Poland' 'Morocco' 'Mexico' 'Italy' 'Iran' 'South Africa' 'Hungary'
 'France' 'Russia' 'Germany' 'Azerbaijan' 'Lebanon' 'Romania'
 'United Arab Emirates' 'Zimbabwe' 'Peru' 'Nigeria' 'Zambia' 'Venezuela'
 'Argentina' 'Seychelles' 'Switzerland' 'United Kingdom' 'China' 'Tunisia'
 'Uganda' 'Belgium' 'India' 'Ukraine' 'New Zealand' 'Taiwan' 'Somalia'
 'Norway' 'Dominican Republic' 'Portugal' 'Paraguay' 'Nicaragua' 'Algeria'
 'Ghana' 'Sierra Leone' 'Namibia' 'Chile' 'Hong Kong S.A.R.' 'Ethiopia'
 'Colombia']
Number of records in 12: 955
Year:   12
['Seychelles' 'Italy' 'Australia' 'Singapore' 'Spain' 'Russia' 'Brazil'
 'Netherlands' 'United Kingdom' 'Chile' 'Germany' 'Kenya' 'Zimbabwe'
 'China' 'Nigeria' 'Cambodia' 'Romania' 'Azerbaijan' 'United States'
 'Turkey' 'Argentina' 'Switzerland' 'Ghana' 'South Africa' 'Uganda'
 'Indonesia' 'Democratic Republic of the Congo' 'Botswana' 'Belgium'
 'Saudi Arabia' 'Ukraine' 'Thailand' 'France' 'Greece' 'Hungary'
 'Bosnia and Herzegovina' 'Republic of Serbia' 'Bulgaria' 'Jordan'
 'Zambia' 'Vietnam' 'Pakistan' 'India' 'Armenia' 'Kazakhstan' 'Canada'
 'United Republic of Tanzania' 'Rwanda' 'Mozambique' 'Dominican Republic'
 'Namibia' 'Uruguay' 'Malaysia' 'Czech Republic' 'Tajikistan' 'Colombia'
 'Uzbekistan' 'Moldova' 'South Korea' 'Yemen' 'Iraq' 'Oman' 'Peru' 'Egypt'

 'Kuwait' 'Nepal' 'Mexico']

#### Remove layers that have been added to the map during processing
This will allow us to control which layers are visible for screenshot capturing.
The pictures could have been captured while the data were being created, but
these steps are separated to make them easier to distinguish.

In [73]:
# aprx is the ArcGIS project object

# Get a list of maps in this project.
myMap = aprx.listMaps('Map')[0]
layers = myMap.listLayers()
layer_object = layers[0]
count = 0 
while "Worldwide" not in layer_object.name and count < len(layers):
    print(layer_object.name)
    myMap.removeLayer(layer_object)
    count = count + 1
    layer_object = layers[count]
    
for i in layers:
    print (i.name)

e12
worldEsther_Layer11
e11
worldEsther_Layer10
e10
worldEsther_Layer9
e9
worldEsther_Layer8
e8
worldEsther_Layer7
e7
worldEsther_Layer6
e6
worldEsther_Layer5
e5
worldEsther_Layer4
e4
worldEsther_Layer3
e3
worldEsther_Layer2
e2
worldEsther_Layer1
e1
worldEsther_Layer
worldEsther

AttributeError: The attribute 'name' is not supported on this instance of Layer.

### Create map layers and take screenshots

We'll do this by looping through the years. Earlier, we created a shapefile for each year.  Now we'll make a layer for each shapefile.   We'll add it to the map, capture a screenshot (a png image), and turn then that layer's visibility off, so that we can do the same again with the next shapefile.

In [74]:
# aprx is the ArcGIS project object

# Get a list of maps in this project.
myMap = aprx.listMaps('Map')[0]

custom_layout = aprx.listLayouts("*surround*")[0]
for elem in custom_layout.listElements():
    print(elem.name)
    if "Text" in elem.name:
        textbox = elem


RGBs = [[190, 210, 255, 60], [245, 122, 122, 60], [255, 255, 0, 60]]

# For each year in the data, add a layer and export an image of it.
for yr in sorted(df_small['Year'].unique()):

    # Get the name of the shapefile associated with the current year. 
    curData = workingDir + f'{baseName}{yr}.shp'
    
    # Add the shapefile as a layer on the map.
    myMap.addDataFromPath(curData)
    # Set the text string to current year
    textbox.text = yr
    
    # Now we need the layer object associated with our new layer. 
    # This gives access to the symbology properties of the layer.  
    # Get a list of layor objects for the layers on this map.
    layerObjects = myMap.listLayers()
    
    # Get the first one (the most recently added to the map)
    lay = layerObjects[0]

    print(lay.name)
    
    sym = lay.symbology
    
    # Set an RGB color for the layer.  
    # Provide the colors as a list of numbers (red, green, and blue, plus alpha for transparency).
    # E.g., [190, 210, 255, 60] is a purple with opacity of 60%.
    theColor = [245, 122, 122, 100]  # pink with no transparency
    sym.renderer.symbol.color = {'RGB': theColor}  

    ## As an alternative to specifying RGB values, you can apply symbology from the gallery.
    # Try something you like.  See the named_symbology_examples.png for other names 
    # or look at the choices in ArcGIS Pro to see more.
    # sym.renderer.symbol.applySymbolFromGallery('Mangrove')

    ## Experiment with the outline by uncommenting the code below
    # sym.renderer.symbol.outlineColor = {'CMYK' : [25, 50, 75, 25, 100]}
    lay.symbology = sym
    #if theMonth == 12:
    #    myMap.defaultView.zoomToAllLayers()
    print ('{}:{}'.format(lay.name, lay.visible))
    outPic = visDir+f'{baseName}{str(yr).zfill(2)}.png'
    #myMap.defaultView.exportToPNG(outPic, width=800, height=600)
    custom_layout.exportToPNG(outPic)
    lay.visible = False
    
    del lay
del myMap
del aprx

Legend
Text
North Arrow
Map Frame
e1
e1:True
e2
e2:True
e3
e3:True
e4
e4:True
e5
e5:True
e6
e6:True
e7
e7:True
e8
e8:True
e9
e9:True
e10
e10:True
e11
e11:True
e12
e12:True

### Creat an animation

In [75]:
import imageio
images = []
import os
mapPics = os.listdir(visDir)

movieName = visDir + '/movie.gif'
if os.path.exists(movieName):
    os.remove(movieName)

for pic in mapPics:
    if pic.endswith("png"):
        images.append(imageio.imread(visDir + pic))


imageio.mimsave(movieName, images, duration=0.8)
image_count = len(images)
print('{} created using {} maps!'.format( movieName, image_count))

[75]:12: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.

C:\Users\echoi4\Desktop\New\esterArcGISProject-20230428T013544Z-001\esterArcGISProject\output\\pics\/movie.gif created using 12 maps!

In [76]:
print(mapPics)

['e01.png', 'e02.png', 'e03.png', 'e04.png', 'e05.png', 'e06.png', 'e07.png', 'e08.png', 'e09.png', 'e10.png', 'e11.png', 'e12.png']

### Create an html display

In [78]:
header = """<!DOCTYPE html>
<html>
<head>
<style>
div.gallery {
  border: 1px solid #ccc;
}

div.gallery:hover {
  border: 1px solid #777;
}

div.gallery img {
  width: 100%;
  height: auto;
}

div.desc {
  padding: 15px;
  text-align: center;
}

* {
  box-sizing: border-box;
}

.responsive {
  padding: 0 6px;
  float: left;
  width: 24.99999%;
}

@media only screen and (max-width: 700px) {
  .responsive {
    width: 49.99999%;
    margin: 6px 0;
  }
}

@media only screen and (max-width: 500px) {
  .responsive {
    width: 100%;
  }
}

.clearfix:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>
<body>
""" 

bodyContent = f"""<h2>{baseName.title()} Posts Over {image_count} Months </h2>
<h4>Author: Grace Choi</h4>
<h4>Data source: {baseName} Tuta Absoluta data</h4>"""

mapPics = os.listdir(visDir)

mapPics = [picName for picName in mapPics if picName.endswith('.png') ]

for pic in mapPics:
    dateVal = os.path.splitext(pic)[0]
    dateVal = dateVal.replace(baseName,'')
    dateVal = int(dateVal)
    bodyContent = bodyContent + f"""<div class="responsive"><div class="gallery">
  <a target="_blank" href={pic}>
    <img src={pic} alt="{os.path.splitext(pic)[0]}" width="800" height="600">
  </a>
  <div class="desc">{yearly_count[dateVal]} {baseName.title()} post(s) in {dateVal}</div>
</div></div>"""

# Add movie
movieName = os.path.basename(movieName)
bodyContent = bodyContent + f"""<div class="responsive"><div class="gallery">
  <a target="_blank" href={movieName}>
    <img src={movieName} alt="animation" width="800" height="600">
  </a>
  <div class="desc">{baseName.title()} posts over time.</div>
</div></div>"""


footer = """</body>
</html>"""

html_file_name = visDir + f'{baseName}.html'

with open( html_file_name,'w') as outFileObject:
  outFileObject.write(header)
  outFileObject.write(bodyContent)
  outFileObject.write(footer)
os.startfile(html_file_name)